<?php if (!defined('ROOT_DIR')) {
    exit;
}

return array(
    'order_id'     => array(
        'field'   => 'order_id',
        'type'    => 'int(11)',
        'null'    => 'NO',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'openId'       => array(
        'field'   => 'openId',
        'type'    => 'varchar(255)',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'ticket_id'    => array(
        'field'   => 'ticket_id',
        'type'    => 'int(11)',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'QR'           => array(
        'field'   => 'QR',
        'type'    => 'text',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'order_title'  => array(
        'field'   => 'order_title',
        'type'    => 'varchar(255)',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'order_sn'     => array(
        'field'   => 'order_sn',
        'type'    => 'varchar(255)',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'order_price'  => array(
        'field'   => 'order_price',
        'type'    => 'decimal(10,0)',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'order_tag'    => array(
        'field'   => 'order_tag',
        'type'    => 'varchar(255)',
        'null'    => 'YES',
        'key'     => false,
        'default' => '门票',
        'extra'   => '',
    ),
    'order_attach' => array(
        'field'   => 'order_attach',
        'type'    => 'varchar(255)',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'order_status' => array(
        'field'   => 'order_status',
        'type'    => 'int(1)',
        'null'    => 'YES',
        'key'     => false,
        'default' => '0',
        'extra'   => '',
    ),
    'order_time'   => array(
        'field'   => 'order_time',
        'type'    => 'int(10)',
        'null'    => 'YES',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'order_type'   => array(
        'field'   => 'order_type',
        'type'    => 'int(1)',
        'null'    => 'NO',
        'key'     => false,
        'default' => '1',
        'extra'   => '',
    ),
    'order_code'   => array(
        'field'   => 'order_code',
        'type'    => 'int(13)',
        'null'    => 'NO',
        'key'     => false,
        'default' => NULL,
        'extra'   => '',
    ),
    'agency_id'    => array(
        'field'   => 'agency_id',
        'type'    => 'int(11)',
        'null'    => 'NO',
        'key'     => false,
        'default' => '0',
        'extra'   => '',
    ),
);
?>